/**
 * PKM export engine — the "Local-First Knowledge" layer.
 *
 * Turns a stored Summary into strict Markdown with Obsidian [[Wiki-Links]]
 * injected around every extracted Entity, then serves Obsidian (write-to-vault
 * or download) and Notion (enhanced with Phase 2 sections).
 */

export interface EntityLike {
  type?: string;
  name?: string;
}

/** Wrap occurrences of entity names in [[Wiki-Links]]. Longest-first so
 *  "Sam Altman" wins over "Altman". Skips already-bracketed or backticked text. */
export function wikiLinkEntities(text: string, entities: EntityLike[] = []): string {
  if (!text || entities.length === 0) return text;
  const names = entities
    .map(e => e?.name)
    .filter((n): n is string => !!n && n.trim().length >= 3)
    .sort((a, b) => b.length - a.length);
  if (names.length === 0) return text;

  const escaped = names.map(n => n.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|');
  const re = new RegExp('(^|[^\\w\\[\\]`])(' + escaped + ')(?![\\w\\]])', 'g');
  return text.replace(re, (m, pre: string, name: string) => `${pre}[[${name}]]`);
}

export function buildKnowledgeMarkdown(input: {
  title: string;
  channel: string;
  videoId: string;
  language?: string;
  executiveSummary: string;
  verdict: string;
  quotes: string[];
  resources: string[];
  frameworks?: { name: string; description: string }[];
  biasAnalysis?: string[];
  entities?: EntityLike[];
  signalDensity?: any | null;
  topicClusters?: { topic: string; summary: string }[] | null;
  freshness?: { claim: string; status: string; note: string }[] | null;
  notes?: string | null;
}): string {
  const {
    title, channel, videoId, language = 'English',
    executiveSummary, verdict, quotes, resources,
    frameworks = [], biasAnalysis = [], entities = [],
    signalDensity, topicClusters, freshness, notes,
  } = input;

  const url = `https://youtube.com/watch?v=${videoId}`;
  const slug = title.replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 80) || 'video';
  const date = new Date().toISOString().slice(0, 10);

  const L: string[] = [];
  L.push('---');
  L.push(`title: "${title.replace(/"/g, "'")}"`);
  L.push(`source: ${url}`);
  L.push(`channel: "${channel.replace(/"/g, "'")}"`);
  L.push(`date: ${date}`);
  L.push(`language: ${language}`);
  L.push(`tags: [synop, ${entities.slice(0, 6).map(e => e.name?.replace(/\s+/g, '-').toLowerCase()).filter(Boolean).join(', ')}]`);
  L.push('---');
  L.push('');
  L.push(`# ${title}`);
  L.push('');
  L.push(`> Channel: ${channel}  `);
  L.push(`> Source: ${url}`);
  L.push('');

  if (signalDensity && signalDensity.density_score != null) {
    L.push(`## Signal Density: ${signalDensity.density_score}%`);
    L.push('');
    L.push(`> ${signalDensity.value_minutes ?? 0} minutes of real value extracted from a ${signalDensity.total_minutes ?? '?'}-minute video.`);
    L.push('');
    if (signalDensity.removed_segments?.length) {
      L.push('Removed: ' + signalDensity.removed_segments.map((s: any) => `${s.type} (${s.approx_minutes} min)`).join(', ') + '.');
      L.push('');
    }
  }

  L.push('## Executive Summary');
  L.push('');
  L.push(wikiLinkEntities(executiveSummary, entities));
  L.push('');

  if (topicClusters && topicClusters.length > 0) {
    L.push('## Topics');
    L.push('');
    for (const t of topicClusters) {
      L.push(`### [[${t.topic}]]`);
      L.push('');
      L.push(wikiLinkEntities(t.summary, entities));
      L.push('');
    }
  }

  if (quotes.length > 0) {
    L.push('## Quotes');
    L.push('');
    for (const q of quotes) L.push(`> ${wikiLinkEntities(q, entities)}`);
    L.push('');
  }

  if (freshness && freshness.length > 0) {
    L.push('## Freshness Check');
    L.push('');
    for (const f of freshness) {
      const badge =
        f.status === 'DEBUNKED_OUTDATED' ? '🔴' :
        f.status === 'CONTEXT_CHANGED' ? '🟡' : '🟢';
      L.push(`- ${badge} **${f.claim}** — ${f.note}`);
    }
    L.push('');
  }

  if (resources.length > 0) {
    L.push('## Resources');
    L.push('');
    for (const r of resources) L.push(`- ${r}`);
    L.push('');
  }

  if (frameworks.length > 0) {
    L.push('## Frameworks');
    L.push('');
    for (const f of frameworks) L.push(`- **${f.name}**: ${f.description}`);
    L.push('');
  }

  if (biasAnalysis.length > 0) {
    L.push('## Bias & Critique');
    L.push('');
    for (const b of biasAnalysis) L.push(`- ${b}`);
    L.push('');
  }

  if (notes) {
    L.push('## Handwritten Notes');
    L.push('');
    L.push(notes);
    L.push('');
  }

  L.push('---');
  L.push(`## Verdict`);
  L.push('');
  L.push(wikiLinkEntities(verdict, entities));
  L.push('');
  L.push(`*Generated by Synop on ${new Date().toLocaleString()}*`);
  L.push('');

  return L.join('\n');
}

/** Safe filename for vault writes. */
export function slugify(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9\s-]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 90);
}
