"use client";

import { useMemo } from "react";
import { FileText, Loader2, AlertCircle, RefreshCw } from "lucide-react";

/**
 * Multi-page handwritten-style lecture notes, generated by /api/notes and
 * ordered by the video's topic clusters. Rendered as ruled notebook pages.
 */

interface Page {
  title: string;
  body: string[];
}

function parsePages(text: string): Page[] {
  const lines = text.split("\n");
  const blocks: Page[] = [];
  let cur: Page | null = null;
  for (const line of lines) {
    const m = line.trim().match(/^=== (.*) ===$/);
    if (m) {
      cur = { title: m[1], body: [] };
      blocks.push(cur);
    } else if (cur) {
      cur.body.push(line);
    }
  }
  if (blocks.length === 0) return [{ title: "Notes", body: lines }];
  return blocks;
}

export default function HandwrittenNotes({
  text,
  loading,
  error,
  onLoad,
}: {
  text: string | null;
  loading: boolean;
  error: string | null;
  onLoad: () => void;
}) {
  const pages = useMemo(() => (text ? parsePages(text) : []), [text]);

  if (loading && !text) {
    return (
      <div className="max-w-2xl mx-auto glass border border-border/50 rounded-3xl p-8 flex flex-col items-center gap-3">
        <Loader2 className="w-6 h-6 text-primary animate-spin" />
        <p className="text-sm font-bold text-foreground/60">Writing your lecture notes…</p>
        <p className="text-xs text-foreground/40">Structured by the video's topics.</p>
      </div>
    );
  }

  if (!text) {
    return (
      <div className="max-w-2xl mx-auto glass border border-border/50 rounded-3xl p-10 text-center">
        {error ? (
          <>
            <AlertCircle className="w-10 h-10 text-destructive/60 mx-auto mb-4" />
            <p className="font-bold text-foreground">Couldn't generate notes</p>
            <p className="text-sm text-foreground/50 mt-1 max-w-md mx-auto">{error}</p>
            <button onClick={onLoad} className="mt-5 h-10 px-5 bg-foreground text-background rounded-xl text-sm font-bold hover:opacity-90 inline-flex items-center gap-2">
              <RefreshCw className="w-4 h-4" /> Try again
            </button>
          </>
        ) : (
          <>
            <FileText className="w-10 h-10 text-foreground/25 mx-auto mb-4" />
            <p className="font-bold text-foreground">Handwritten-style lecture notes</p>
            <p className="text-sm text-foreground/50 mt-1 max-w-md mx-auto">Turn this video into multi-page study notes, organized by its topic clusters.</p>
            <button onClick={onLoad} className="mt-5 h-10 px-6 bg-primary text-white rounded-xl text-sm font-bold hover:opacity-90">
              Generate Notes
            </button>
          </>
        )}
      </div>
    );
  }

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      {pages.map((p, i) => (
        <div
          key={i}
          className="relative bg-[#fdfaf3] dark:bg-[#201f1c] rounded-[6px] shadow-[0_10px_30px_-12px_rgba(0,0,0,0.35)] px-8 pb-8 pt-4"
          style={{
            fontFamily: "'Marker Felt','Bradley Hand','Segoe Print','Comic Sans MS',cursive",
            backgroundImage:
              "repeating-linear-gradient(transparent, transparent 31px, rgba(120,110,90,0.18) 31px, rgba(120,110,90,0.18) 32px)",
            lineHeight: "32px",
            color: "#3a3429",
            transform: `rotate(${i % 2 === 0 ? -0.3 : 0.35}deg)`,
          }}
        >
          <div className="h-6 mb-2 border-b border-[#d8b4c0]/50 dark:border-[#4a3f3a]/50" />
          <h4 className="text-lg font-bold tracking-wide" style={{ color: "#b24a5b" }}>
            {p.title.replace(/^PAGE \d+:\s*/i, "")}
          </h4>
          <div className="whitespace-pre-wrap text-[14px] leading-[32px]">
            {p.body.length ? p.body.join("\n") : " "}
          </div>
        </div>
      ))}
    </div>
  );
}
